import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, SafeAreaView, Text, TouchableOpacity, View } from 'react-native';
import { getOrders } from '../services/orderService';

export default function OrderHistoryScreen({ token }: { token: string | null }): React.JSX.Element {
  const [orders, setOrders] = useState<any[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false);
  const load = useCallback(async (nextPage = 1, nextStatus = status) => { if (!token) return; setLoading(true); try { const data = await getOrders(token, nextPage, { status: nextStatus || undefined }); setOrders((old) => nextPage === 1 ? data.orders : [...old, ...data.orders]); setPage(data.page); setPages(data.pages); } catch (e) { console.warn('Could not load orders', e); } finally { setLoading(false); } }, [token, status]);
  useEffect(() => { load(1); }, [load]);
  const filter = (value: string) => { setStatus(value); setOrders([]); setPage(1); };
  return <SafeAreaView style={{ flex: 1, backgroundColor: '#F8F6F1' }}><Text style={{ fontSize: 25, fontWeight: '800', color: '#294936', margin: 18 }}>Order history</Text><View style={{ flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12 }}>{['', 'PENDING', 'COMPLETED', 'CANCELLED'].map((item) => <TouchableOpacity key={item || 'all'} onPress={() => filter(item)} style={{ padding: 9, backgroundColor: status === item ? '#DDEBE0' : 'white', borderRadius: 10 }}><Text>{item || 'All'}</Text></TouchableOpacity>)}</View>{loading && orders.length === 0 ? <ActivityIndicator /> : <FlatList data={orders} keyExtractor={(o) => o._id} onEndReached={() => { if (!loading && page < pages) load(page + 1); }} renderItem={({ item }) => <View style={{ marginHorizontal: 16, marginVertical: 6, padding: 16, backgroundColor: 'white', borderRadius: 16 }}><Text style={{ fontWeight: '800' }}>Order {item._id.slice(-8)} · {item.status}</Text><Text style={{ marginTop: 5, color: '#718078' }}>{new Date(item.createdAt).toLocaleDateString()}</Text>{item.items.map((line: any, i: number) => <Text key={i} style={{ marginTop: 6 }}>{line.productId?.name || 'Product'} × {line.quantity} · ₹{line.price}</Text>)}<Text style={{ marginTop: 8, fontWeight: '700' }}>Total ₹{item.totalAmount}</Text></View>} ListEmptyComponent={<Text style={{ padding: 20 }}>No orders found.</Text>} />}</SafeAreaView>;
}
