import React, { useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, Switch, Text, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { defaults, loadPreferences, Preferences, savePreferences, ThemePreference } from '../services/preferencesService';

const THEME_KEY = '@theme_preference';
const categories = [['order', 'Order confirmations'], ['payment', 'Payment updates'], ['shipping', 'Shipping and delivery'], ['wishlist', 'Wishlist and stock alerts'], ['promotions', 'Promotions'], ['cart', 'Cart reminders']];
export default function PreferencesScreen({ token }: { token: string | null }): React.JSX.Element {
  const [prefs, setPrefs] = useState<Preferences>(defaults);
  const [loading, setLoading] = useState(!!token);
  useEffect(() => { (async () => { const local = await AsyncStorage.getItem(THEME_KEY); if (local === 'light' || local === 'dark' || local === 'system') setPrefs((p) => ({ ...p, themePreference: local })); if (token) { try { const remote = await loadPreferences(token); setPrefs(remote); await AsyncStorage.setItem(THEME_KEY, remote.themePreference); } catch (e) { console.warn('Could not sync preferences', e); } } setLoading(false); })(); }, [token]);
  const update = async (delta: Partial<Preferences>) => { const next = { ...prefs, ...delta }; setPrefs(next); if (delta.themePreference) await AsyncStorage.setItem(THEME_KEY, delta.themePreference); if (token) try { const saved = await savePreferences(token, delta); setPrefs(saved); } catch (e) { console.warn('Preference sync failed', e); } };
  return <SafeAreaView style={{ flex: 1, backgroundColor: '#F8F6F1' }}><ScrollView contentContainerStyle={{ padding: 20 }}><Text style={{ fontSize: 26, fontWeight: '800', color: '#294936', marginBottom: 18 }}>Personalization</Text><Text style={{ fontSize: 17, fontWeight: '700', marginBottom: 10 }}>Appearance</Text><View style={{ flexDirection: 'row', marginBottom: 25 }}>{(['system', 'light', 'dark'] as ThemePreference[]).map((theme) => <TouchableOpacity key={theme} onPress={() => update({ themePreference: theme })} style={{ padding: 12, marginRight: 8, borderRadius: 12, backgroundColor: prefs.themePreference === theme ? '#6B8F71' : 'white' }}><Text style={{ color: prefs.themePreference === theme ? 'white' : '#243027', textTransform: 'capitalize' }}>{theme}</Text></TouchableOpacity>)}</View><Text style={{ fontSize: 17, fontWeight: '700', marginBottom: 8 }}>Notifications</Text>{loading && <ActivityIndicator />}{categories.map(([key, label]) => <View key={key} style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#E3E8E3' }}><Text style={{ color: '#243027' }}>{label}</Text><Switch value={prefs.notificationPreferences[key] !== false} onValueChange={(value) => update({ notificationPreferences: { ...prefs.notificationPreferences, [key]: value } })} trackColor={{ true: '#6B8F71' }} /></View>)}{!token && <Text style={{ marginTop: 18, color: '#718078' }}>Sign in to sync preferences across devices.</Text>}</ScrollView></SafeAreaView>;
}
